// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BUIZ3NVRjdzMNDYvcJ0fEwtjUf9uGRo',
    appId: '1:323874168311:web:415b90db5968e3456122f2',
    messagingSenderId: '323874168311',
    projectId: 'social-media-25e24',
    authDomain: 'social-media-25e24.firebaseapp.com',
    storageBucket: 'social-media-25e24.appspot.com',
    measurementId: 'G-WKG2SHR83N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bUslSZWNSE_ntYeYGWbDirWj15N5VxQ',
    appId: '1:323874168311:android:ed188e5222a3bfde6122f2',
    messagingSenderId: '323874168311',
    projectId: 'social-media-25e24',
    storageBucket: 'social-media-25e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITaTzUZAHWYzAfPNWPGPt2rP--HnSfos',
    appId: '1:323874168311:ios:85f723f53fb177776122f2',
    messagingSenderId: '323874168311',
    projectId: 'social-media-25e24',
    storageBucket: 'social-media-25e24.appspot.com',
    iosClientId: '323874168311-idkdsifmmeog4u2s6u7toe5e08vm7cus.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITaTzUZAHWYzAfPNWPGPt2rP--HnSfos',
    appId: '1:323874168311:ios:85f723f53fb177776122f2',
    messagingSenderId: '323874168311',
    projectId: 'social-media-25e24',
    storageBucket: 'social-media-25e24.appspot.com',
    iosClientId: '323874168311-idkdsifmmeog4u2s6u7toe5e08vm7cus.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
